version: '2'

services: 
  auto-tests:
    build:
      context: .
      args:
        HTTP_CREDENTIALS_USERNAME: ${HTTP_CREDENTIALS_USERNAME}
        HTTP_CREDENTIALS_PASSWORD: ${HTTP_CREDENTIALS_PASSWORD}

